//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warframe.Market_Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityContext : DbContext
    {
        public EntityContext()
            : base("name=EntityContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<ItemTag> ItemTag { get; set; }
        public virtual DbSet<LinkedAccounts> LinkedAccounts { get; set; }
        public virtual DbSet<LoginUser> LoginUser { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<SetItem> SetItem { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<Translation> Translation { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<IconFormatType> IconFormatType { get; set; }
        public virtual DbSet<OrderType> OrderType { get; set; }
        public virtual DbSet<PlatformType> PlatformType { get; set; }
        public virtual DbSet<RegionType> RegionType { get; set; }
        public virtual DbSet<RoleType> RoleType { get; set; }
        public virtual DbSet<StatusType> StatusType { get; set; }
        public virtual DbSet<SubTypeType> SubTypeType { get; set; }
    }
}
