//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warframe.Market_Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LinkedAccounts()
        {
            this.LoginUser = new HashSet<LoginUser>();
        }
    
        public int ID { get; set; }
        public bool HasSteamProfile { get; set; }
        public bool HasPatreonProfile { get; set; }
        public bool HasXboxProfile { get; set; }
        public bool HasDiscordProfile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginUser> LoginUser { get; set; }
    }
}
