//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warframe.Market_Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUser
    {
        public int ID { get; set; }
        public string CheckCode { get; set; }
        public Nullable<bool> Banned { get; set; }
        public Nullable<bool> Anonymous { get; set; }
        public Nullable<bool> HasMail { get; set; }
        public Nullable<bool> Verification { get; set; }
        public Nullable<byte> UnreadMessages { get; set; }
        public Nullable<byte> WrittenReviews { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PlatformID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> LinkedAccountsID { get; set; }
    
        public virtual LinkedAccounts LinkedAccounts { get; set; }
        public virtual PlatformType PlatformType { get; set; }
        public virtual RoleType RoleType { get; set; }
        public virtual User User { get; set; }
    }
}
