//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warframe.Market_Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public System.DateTimeOffset CreationDate { get; set; }
        public System.DateTimeOffset LastUpdate { get; set; }
        public int Quantity { get; set; }
        public bool Visible { get; set; }
        public int Platinum { get; set; }
        public Nullable<byte> ModRank { get; set; }
        public int UserID { get; set; }
        public int PlatformTypeID { get; set; }
        public int RegionTypeID { get; set; }
        public int OrderTypeID { get; set; }
    
        public virtual OrderType OrderType { get; set; }
        public virtual PlatformType PlatformType { get; set; }
        public virtual RegionType RegionType { get; set; }
        public virtual User User { get; set; }
    }
}
